attempts: 3.0       # Amount of incorrect login attempts before locking user out
attempt_reset: 1.0  # Amount of minutes after an attempt that the attempts counter resets
lockout: 3.0        # Amount of minutes a user is locked out for
